import _ from 'lodash';

export const SubjectMap = [
    { key: 'AAS', value: 'Asian American Studies' },
    { key: 'ABE', value: 'Agricultural and Biological Engineering' },
    { key: 'ACCY', value: 'Accountancy' },
    { key: 'ACE', value: 'Agricultural and Consumer Economics' },
    { key: 'ACES', value: 'Agricultural, Consumer and Environmental Sciences' },
    { key: 'ADV', value: 'Advertising' },
    { key: 'AE', value: 'Aerospace Engineering' },
    { key: 'AFAS', value: 'Air Force Aerospace Studies' },
    { key: 'AFRO', value: 'African American Studies' },
    { key: 'AFST', value: 'African Studies' },
    { key: 'AGCM', value: 'Agricultural Communications' },
    { key: 'AGED', value: 'Agricultural Education' },
    { key: 'AHS', value: 'Applied Health Sciences Courses' },
    { key: 'AIS', value: 'American Indian Studies' },
    { key: 'ANSC', value: 'Animal Sciences' },
    { key: 'ANTH', value: 'Anthropology' },
    { key: 'ARAB', value: 'Arabic' },
    { key: 'ARCH', value: 'Architecture' },
    { key: 'ART', value: 'Art' },
    { key: 'ARTD', value: 'Art--Design' },
    { key: 'ARTE', value: 'Art--Education' },
    { key: 'ARTF', value: 'Art--Foundation' },
    { key: 'ARTH', value: 'Art--History' },
    { key: 'ARTS', value: 'Art--Studio' },
    { key: 'ASST', value: 'Asian Studies' },
    { key: 'ASTR', value: 'Astronomy' },
    { key: 'ATMS', value: 'Atmospheric Sciences' },
    { key: 'BADM', value: 'Business Administration' },
    { key: 'BASQ', value: 'Basque' },
    { key: 'BCS', value: 'Bosnian-Croatian-Serbian' },
    { key: 'BIOC', value: 'Biochemistry' },
    { key: 'BIOE', value: 'Bioengineering' },
    { key: 'BIOL', value: 'Biology' },
    { key: 'BIOP', value: 'Biophysics' },
    { key: 'BTW', value: 'Business and Technical Writing' },
    { key: 'BUS', value: 'Business' },
    { key: 'CAS', value: 'Center for Advanced Study' },
    { key: 'CB', value: 'Comparative Biosciences' },
    { key: 'CDB', value: 'Cell and Developmental Biology' },
    { key: 'CEE', value: 'Civil and Environmental Engineering' },
    { key: 'CHBE', value: 'Chemical and Biomolecular Engineering' },
    { key: 'CHEM', value: 'Chemistry' },
    { key: 'CHIN', value: 'Chinese' },
    { key: 'CHLH', value: 'Community Health' },
    { key: 'CHP', value: 'Campus Honors Program Courses' },
    { key: 'CI', value: 'Curriculum and Instruction' },
    { key: 'CIC', value: 'Committee on Inst Cooperation' },
    { key: 'CLCV', value: 'Classical Civilization' },
    { key: 'CMN', value: 'Communication' },
    { key: 'CPSC', value: 'Crop Sciences' },
    { key: 'CS', value: 'Computer Science' },
    { key: 'CSE', value: 'Computational Science and Engineering' },
    { key: 'CW', value: 'Creative Writing' },
    { key: 'CWL', value: 'Comparative and World Literature' },
    { key: 'CZCH', value: 'Czech' },
    { key: 'DANC', value: 'Dance' },
    { key: 'EALC', value: 'East Asian Language and Culture' },
    { key: 'ECE', value: 'Electrical and Computer Engineering' },
    { key: 'ECON', value: 'Economics' },
    { key: 'EDPR', value: 'Educational Practice' },
    { key: 'EDUC', value: 'Education' },
    { key: 'EIL', value: 'English as an International Language' },
    { key: 'ENG', value: 'Engineering' },
    { key: 'ENGH', value: 'Engineering Honors' },
    { key: 'ENGL', value: 'English' },
    { key: 'ENSU', value: 'Environmental Sustainability' },
    { key: 'ENT', value: 'Entomology' },
    { key: 'ENVS', value: 'Environmental Studies' },
    { key: 'EOL', value: 'Educational Organization and Leadership' },
    { key: 'EPOL', value: 'Education Policy, Organization and Leadership' },
    { key: 'EPS', value: 'Educational Policy Studies' },
    { key: 'EPSY', value: 'Educational Psychology' },
    { key: 'ESE', value: 'Earth, Society, and Environment' },
    { key: 'ESL', value: 'English as a Second Language' },
    { key: 'EURO', value: 'European Union Studies' },
    { key: 'FAA', value: 'Fine and Applied Arts' },
    { key: 'FIN', value: 'Finance' },
    { key: 'FLTE', value: 'Foreign Language Teacher Education' },
    { key: 'FR', value: 'French' },
    { key: 'FSHN', value: 'Food Science and Human Nutrition' },
    { key: 'GC', value: 'Graduate College' },
    { key: 'GCL', value: 'Grand Challenge Learning' },
    { key: 'GEOG', value: 'Geography' },
    { key: 'GEOL', value: 'Geology' },
    { key: 'GER', value: 'German' },
    { key: 'GLBL', value: 'Global Studies' },
    { key: 'GMC', value: 'Germanic' },
    { key: 'GRK', value: 'Greek' },
    { key: 'GRKM', value: 'Modern Greek' },
    { key: 'GS', value: 'General Studies' },
    { key: 'GWS', value: 'Gender and Women\'s Studies' },
    { key: 'HDFS', value: 'Human Development and Family Studies' },
    { key: 'HEBR', value: 'Hebrew, Modern and Classical' },
    { key: 'HIST', value: 'History' },
    { key: 'HNDI', value: 'Hindi' },
    { key: 'HORT', value: 'Horticulture' },
    { key: 'HRD', value: 'Human Resource Development' },
    { key: 'HUM', value: 'Humanities Courses' },
    { key: 'IB', value: 'Integrative Biology' },
    { key: 'IE', value: 'Industrial Engineering' },
    { key: 'IHLT', value: 'i-Health Program' },
    { key: 'INFO', value: 'Informatics' },
    { key: 'IS', value: 'Information Sciences' },
    { key: 'ITAL', value: 'Italian' },
    { key: 'JAPN', value: 'Japanese' },
    { key: 'JOUR', value: 'Journalism' },
    { key: 'JS', value: 'Jewish Studies' },
    { key: 'KIN', value: 'Kinesiology' },
    { key: 'KOR', value: 'Korean' },
    { key: 'LA', value: 'Landscape Architecture' },
    { key: 'LAS', value: 'Liberal Arts and Sciences' },
    { key: 'LAST', value: 'Latin American and Caribbean Studies' },
    { key: 'LAT', value: 'Latin' },
    { key: 'LAW', value: 'Law' },
    { key: 'LER', value: 'Labor and Employment Relations' },
    { key: 'LING', value: 'Linguistics' },
    { key: 'LLS', value: 'Latina/Latino Studies' },
    { key: 'MACS', value: 'Media and Cinema Studies' },
    { key: 'MATH', value: 'Mathematics' },
    { key: 'MBA', value: 'Regular MBA Program Administration' },
    { key: 'MCB', value: 'Molecular and Cell Biology' },
    { key: 'MDIA', value: 'Media' },
    { key: 'MDVL', value: 'Medieval Studies' },
    { key: 'ME', value: 'Mechanical Engineering' },
    { key: 'MICR', value: 'Microbiology' },
    { key: 'MILS', value: 'Military Science' },
    { key: 'MIP', value: 'Molecular and Integrative Physiology' },
    { key: 'MSE', value: 'Materials Science and Engineering' },
    { key: 'MUS', value: 'Music' },
    { key: 'MUSE', value: 'Museum Studies' },
    { key: 'NEUR', value: 'Neuroscience' },
    { key: 'NPRE', value: 'Nuclear, Plasma, and Radiological Engineering' },
    { key: 'NRES', value: 'Natural Resources and Environmental Sciences' },
    { key: 'NS', value: 'Naval Science' },
    { key: 'NUTR', value: 'Nutritional Sciences' },
    { key: 'PATH', value: 'Pathobiology' },
    { key: 'PBIO', value: 'Plant Biology' },
    { key: 'PERS', value: 'Persian' },
    { key: 'PHIL', value: 'Philosophy' },
    { key: 'PHYS', value: 'Physics' },
    { key: 'PLPA', value: 'Plant Pathology' },
    { key: 'POL', value: 'Polish' },
    { key: 'PORT', value: 'Portuguese' },
    { key: 'PS', value: 'Political Science' },
    { key: 'PSM', value: 'Professional Science Master\'s Program' },
    { key: 'PSYC', value: 'Psychology' },
    { key: 'REES', value: 'Russian, East European and Eurasian Studies' },
    { key: 'REHB', value: 'Rehabilitation Counseling' },
    { key: 'REL', value: 'Religion' },
    { key: 'RHET', value: 'Rhetoric and Composition' },
    { key: 'RST', value: 'Recreation, Sport, and Tourism' },
    { key: 'RUSS', value: 'Russian' },
    { key: 'SAME', value: 'South Asian and Middle Eastern Studies' },
    { key: 'SBC', value: 'Strategic Brand Communication' },
    { key: 'SCAN', value: 'Scandinavian' },
    { key: 'SE', value: 'Systems Engineering and Design' },
    { key: 'SHS', value: 'Speech and Hearing Science' },
    { key: 'SLAV', value: 'Slavic' },
    { key: 'SLCL', value: 'Literatures, Cultures, and Linguistics' },
    { key: 'SLS', value: 'Second Language Studies' },
    { key: 'SOC', value: 'Sociology' },
    { key: 'SOCW', value: 'Social Work' },
    { key: 'SPAN', value: 'Spanish' },
    { key: 'SPED', value: 'Special Education' },
    { key: 'STAT', value: 'Statistics' },
    { key: 'SWAH', value: 'Swahili' },
    { key: 'TAM', value: 'Theoretical and Applied Mechanics' },
    { key: 'TE', value: 'Technology Entrepreneurship' },
    { key: 'THEA', value: 'Theatre' },
    { key: 'TMGT', value: 'Technology and Management Courses' },
    { key: 'TRST', value: 'Translation Studies' },
    { key: 'TSM', value: 'Technical Systems Management' },
    { key: 'TURK', value: 'Turkish' },
    { key: 'UKR', value: 'Ukrainian' },
    { key: 'UP', value: 'Urban and Regional Planning' },
    { key: 'VCM', value: 'Veterinary Clinical Medicine' },
    { key: 'VM', value: 'Veterinary Medicine Courses' },
    { key: 'WGGP', value: 'Women and Gender in Global Perspectives Program' },
    { key: 'WLOF', value: 'Wolof' },
    { key: 'WRIT', value: 'Writing Studies' },
    { key: 'YDSH', value: 'Yiddish' },
    { key: 'ZULU', value: 'Zulu' }
];

export const SubjectKeys = _.map(SubjectMap, 'key');

export const SubjectMapForward = (v) => {
    return _.find(SubjectMap, ({ key }) => key === v);
};

export const SubjectMapBlurSearch = (v) => {
    v = _.lowerCase(v);
    return _.uniqBy(_.concat(
        _.filter(SubjectMap, ({ key, value }) => _.lowerCase(key).indexOf(v) !== -1),
        _.filter(SubjectMap, ({ key, value }) => _.lowerCase(value).indexOf(v) !== -1)
    ), 'key');
};
